In [1]:
# Write a NumPy program to test whether none of the elements of a given array is zero.

import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


Original array:
[1 2 3 4 5]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3 4]
Test if none of the elements of the said array is zero:
False


In [1]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))


Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


In [2]:
# Write a NumPy program to create an array of all the even integers from 30 to 70.

import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [3]:
# Write a NumPy program to create a 3x3 identity matrix.

import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Write a NumPy program to create a 3X4 array using and iterate over it.

import numpy as np
a = np.arange(1,13).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Each element of the array is:
1 2 3 4 5 6 7 8 9 10 11 12 

In [5]:
# Write a NumPy program to find the number of rows and columns of a given matrix. 

import numpy as np
m= np.arange(1,13).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)


Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Number of rows and columns of the said matrix:
(3, 4)


In [6]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0. 

import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [8]:
# Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.

import numpy as np
x = np.arange(1, 100)
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [9]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height. 

import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('Akash', 5, 48.5), ('Akshay', 6, 52.5),('Pratik', 5, 42.10), ('Priya', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    


Original array:
[(b'Akash', 5, 48.5 ) (b'Akshay', 6, 52.5 ) (b'Pratik', 5, 42.1 )
 (b'Priya', 5, 40.11)]
Sort by height
[(b'Priya', 5, 40.11) (b'Pratik', 5, 42.1 ) (b'Akash', 5, 48.5 )
 (b'Akshay', 6, 52.5 )]


In [11]:
# Write a NumPy program to count the number of "P" in a given array, element-wise.

import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Number of ‘P’:")
r = np.char.count(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'html']
Number of ‘P’:
[1 2 0 0]


In [12]:
# Write a NumPy program to replace "PHP" with "Python" in the element of a given array.

import numpy as np
x = np.array(['PHP, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)



Original Array:
['PHP, Practice, Solution']

New array:
['Python, Practice, Solution']


In [14]:
#  Write a NumPy program to insert a space between characters of all the elements of a given array. 

import numpy as np
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)


Original Array:
['python' 'PHP' 'java' 'C++']
['p y t h o n' 'P H P' 'j a v a' 'C + +']


In [15]:
# Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

import numpy as np
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)


Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


In [16]:
# Write a NumPy program to repeat all the elements three times of a given array of string.

import numpy as np
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)


Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']
